# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Reading difficult things
tagline:             'one week at a time'
description:         'Reading and summarizing one random scientific paper a week. Made by <a href="https://mobeets.github.io">mobeets</a>.'
url:                 https://mobeets.github.io
baseurl:             https://mobeets.github.io/reading-difficult-things
paginate:            5

# About/contact
author:
  name:              Jay Hennig
  url:               https://twitter.com/jehosafet
  email:             mobeets@gmail.com

# Custom vars
version:             1.0.0

# Gems
gems: [jekyll-paginate]
