# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Paper Trails
tagline:             'by <a href="https://mobeets.github.io">Jay H</a>'
description:         'Reading and summarizing one scientific paper on a different topic each week. Made by <a href="https://mobeets.github.io">Jay Hennig</a>.'
url:                 https://mobeets.github.io/paper-trails
baseurl:             https://mobeets.github.io/paper-trails
paginate:            5

# About/contact
author:
  shortname:	     Jay H
  name:              Jay Hennig
  url:               https://twitter.com/jehosafet
  email:             mobeets@gmail.com

# Custom vars
version:             1.0.0

# Gems
gems: [jekyll-paginate]
markdown: kramdown

# Run with:
# bundle exec jekyll serve --baseurl ''
